name: Scheduled Workflow

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         
      - name: Run a script
        run: |
         chmod +x ./ratio-spoof
         ./ratio-spoof -t fl.torrent -d 100% -ds 1053kbps -u 100% -us 0kbps -c qbit-4.6.5 -p 63857
