name: seed

on:
  workflow_dispatch:
    inputs:
      seed:
        description: Use TL? (0=MAM, 1=TL)
        required: true

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Seed TL
        if: github.event.inputs.seed == '1'
        run: |
         chmod +x ./ratio-spoof
         ./ratio-spoof -t fl.torrent -d 100% -ds 1053kbps -u 100% -us 0kbps -c qbit-4.6.5 -p 63857


      - name: Seed MAM
        if: github.event.inputs.seed == '0'
        run: |
         chmod +x ./ratio-spoof
         ./ratio-spoof -t wo.torrent -d 100% -ds 0kbps -u 0% -us 4414kbps -c qbit-4.3.9 -p 63857
        
